"""empty message

Revision ID: bc91f616f7e7
Revises: 
Create Date: 2023-03-06 16:45:46.498275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc91f616f7e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=False),
    sa.Column('firstName', sa.String(length=15), nullable=False),
    sa.Column('lastName', sa.String(length=15), nullable=False),
    sa.Column('hashed_password', sa.String(length=1000), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('profileImg', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.String(length=255), nullable=False),
    sa.Column('updatedAt', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=75), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('resort', sa.String(length=100), nullable=False),
    sa.Column('difficulty', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('elevation', sa.Integer(), nullable=False),
    sa.Column('routeType', sa.String(length=100), nullable=False),
    sa.Column('previewImg', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.String(length=255), nullable=False),
    sa.Column('updatedAt', sa.String(length=255), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trailId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(length=500), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('reviewImg', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.String(length=255), nullable=False),
    sa.Column('updatedAt', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['trailId'], ['trails.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('trails')
    op.drop_table('users')
    # ### end Alembic commands ###
